//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Educ5Ver2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Checks = new HashSet<Checks>();
        }
    
        public int ID_Order { get; set; }
        public System.DateTime Order_Date { get; set; }
        public decimal Total_Amount { get; set; }
        public decimal Deposited { get; set; }
        public decimal Change_Amount { get; set; }
        public int Point_ID { get; set; }
        public int Order_Employee_ID { get; set; }
        public int Client_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checks> Checks { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Pickup_Points Pickup_Points { get; set; }
    }
}
