//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Educ5Ver2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Checks = new HashSet<Checks>();
        }
    
        public int ID_Product { get; set; }
        public string Product_Name { get; set; }
        public decimal Price { get; set; }
        public bool Availible { get; set; }
        public int Category_ID { get; set; }
        public int Provider_ID { get; set; }
        public int Maker_ID { get; set; }
    
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checks> Checks { get; set; }
        public virtual Makers Makers { get; set; }
        public virtual Providers Providers { get; set; }
    }
}
